import React from 'react';
import { Pressable, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { useUPConfig } from '../../config/useUPConfig';
import { getPx, type UPDimension } from '../../utils';
import { UPIcon } from '../icon';
import { useUPRadioContext, type UPChoiceName } from '../selection-context';
export type UPRadioSlotPayload={checked:boolean;iconSize:number;iconColor:string;disabled:boolean};
export type UPRadioProps={name?:UPChoiceName;shape?:'circle'|'square';disabled?:boolean|string;labelDisabled?:boolean|string;activeColor?:string;inactiveColor?:string;iconSize?:UPDimension;labelSize?:UPDimension;label?:string|number;size?:UPDimension;iconColor?:string;labelColor?:string;/** Source icon color, alias with lower priority than `iconColor`. */color?:string;customStyle?:StyleProp<ViewStyle>;customClass?:string;children?:React.ReactNode;
/** Source `icon` scoped slot: receives resolved icon state from the group. */
iconNode?:React.ReactNode|((payload:UPRadioSlotPayload)=>React.ReactNode);
/** Source `label` scoped slot: receives the label and resolved disabled state. */
labelNode?:React.ReactNode|((payload:{label:string|number|undefined;disabled:boolean})=>React.ReactNode);
onChange?:(value:UPChoiceName)=>void;};
export function UPRadio(input:UPRadioProps):React.JSX.Element {const config=useUPConfig();const props={...config.props.radio,...input};const group=useUPRadioContext();const name=props.name;const checked=group?.value===name;const disabled=Boolean(props.disabled)||Boolean(group?.disabled);const size=getPx(props.size||group?.size||18);const active=props.activeColor||group?.activeColor||'#2979ff';const inactive=props.inactiveColor||group?.inactiveColor||'#c8c9cc';const select=()=>{if(disabled)return;group?.onChange(name);input.onChange?.(name)};const resolvedIconSize=getPx(props.iconSize||group?.iconSize||12);const resolvedIconColor=props.color||props.iconColor||group?.iconColor||'#ffffff';const slotPayload:UPRadioSlotPayload={checked,disabled,iconColor:resolvedIconColor,iconSize:resolvedIconSize};const defaultIcon=<View style={{alignItems:'center',backgroundColor:checked&&!disabled?active:'#ffffff',borderColor:checked&&!disabled?active:inactive,borderRadius:(props.shape||group?.shape)==='square'?3:100,borderWidth:1,height:size,justifyContent:'center',width:size}}>{checked?<UPIcon color={resolvedIconColor} name="checkbox-mark" size={resolvedIconSize}/>:null}</View>;const icon=input.iconNode===undefined?defaultIcon:(typeof input.iconNode==='function'?input.iconNode(slotPayload):input.iconNode);const defaultLabel=<Text style={{color:disabled?inactive:props.labelColor||group?.labelColor||'#303133',fontSize:getPx(props.labelSize||group?.labelSize||14),marginHorizontal:6}}>{input.children??props.label}</Text>;const label=input.labelNode===undefined?defaultLabel:(typeof input.labelNode==='function'?input.labelNode({disabled,label:props.label}):input.labelNode);return <Pressable accessibilityRole="radio" accessibilityState={{checked,disabled}} disabled={disabled} onPress={select} style={[{alignItems:'center',flexDirection:group?.iconPlacement==='right'?'row-reverse':'row',opacity:disabled?.6:1},input.customStyle]} testID={`up-radio-${String(name)}`}>{icon}{props.label!==''||input.children?label:null}</Pressable>}
