/**
 * UPIcon 组件示例 — 图标
 * 复刻 uview-plus pages/componentsA/icon/icon.nvue
 */
import React, { useState } from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { UPIcon } from 'ultra-ui-rn';
import { DemoPage, PropsTable, EventLog } from '../_shared';

const PROPS = [
  { prop: 'name', type: 'UPIconName | string', default: '—', desc: '图标名称，或图片路径' },
  { prop: 'color', type: 'string', default: '#606266', desc: '图标颜色' },
  { prop: 'size', type: 'UPDimension', default: "'16px'", desc: '图标字体大小' },
  { prop: 'bold', type: 'boolean', default: 'false', desc: '是否显示粗体' },
  { prop: 'index', type: 'string | number', default: '—', desc: '点击图标时返回的索引' },
  { prop: 'customPrefix', type: 'string', default: "'uicon'", desc: '自定义字体图标库时的字体名' },
  { prop: 'label', type: 'string | number', default: '—', desc: '图标附带的文字' },
  { prop: 'labelPos', type: "'left' | 'right' | 'top' | 'bottom'", default: "'right'", desc: 'label 相对于图标的位置' },
  { prop: 'labelSize', type: 'UPDimension', default: "'15px'", desc: 'label 字体大小' },
  { prop: 'labelColor', type: 'string', default: '#606266', desc: 'label 字体颜色' },
  { prop: 'space', type: 'UPDimension', default: "'3px'", desc: 'label 与图标的距离' },
  { prop: 'imgMode', type: 'string', default: '—', desc: '图片裁剪缩放模式' },
  { prop: 'width', type: 'UPDimension', default: '—', desc: '图片宽度' },
  { prop: 'height', type: 'UPDimension', default: '—', desc: '图片高度' },
  { prop: 'top', type: 'UPDimension', default: '0', desc: '图标垂直方向的偏移量' },
  { prop: 'stop', type: 'boolean', default: 'false', desc: '是否阻止事件传播（RN 无对应能力，no-op）' },
];

const iconList = [
  { name: 'level' },
  { name: 'woman' },
  { name: 'man' },
  { name: 'arrow-left-double' },
  { name: 'arrow-right-double' },
  { name: 'chat' },
  { name: 'chat-fill' },
  { name: 'red-packet' },
  { name: 'red-packet-fill' },
  { name: 'order' },
  { name: 'checkbox-mark' },
  { name: 'arrow-up-fill' },
  { name: 'arrow-down-fill' },
  { name: 'backspace' },
  { name: 'photo' },
  { name: 'photo-fill' },
  { name: 'lock' },
  { name: 'lock-fill' },
  { name: 'lock-open' },
  { name: 'lock-opened-fill' },
  { name: 'hourglass' },
  { name: 'hourglass-half-fill' },
  { name: 'home' },
  { name: 'home-fill' },
  { name: 'fingerprint' },
  { name: 'cut' },
  { name: 'star' },
  { name: 'star-fill' },
  { name: 'share' },
  { name: 'share-fill' },
  { name: 'volume' },
  { name: 'volume-fill' },
  { name: 'volume-off' },
  { name: 'volume-off-fill' },
  { name: 'trash' },
  { name: 'trash-fill' },
  { name: 'rewind-right' },
  { name: 'rewind-right-fill' },
  { name: 'rewind-left' },
  { name: 'rewind-left-fill' },
  { name: 'shopping-cart' },
  { name: 'shopping-cart-fill' },
  { name: 'question' },
  { name: 'question-circle' },
  { name: 'question-circle-fill' },
  { name: 'plus' },
  { name: 'plus-circle' },
  { name: 'plus-circle-fill' },
  { name: 'tags' },
  { name: 'tags-fill' },
  { name: 'pause' },
  { name: 'pause-circle' },
  { name: 'pause-circle-fill' },
  { name: 'play-circle' },
  { name: 'play-circle-fill' },
  { name: 'map' },
  { name: 'map-fill' },
  { name: 'phone' },
  { name: 'phone-fill' },
  { name: 'list' },
  { name: 'list-dot' },
  { name: 'man-delete' },
  { name: 'man-add' },
  { name: 'man-add-fill' },
  { name: 'person-delete-fill' },
  { name: 'info' },
  { name: 'info-circle' },
  { name: 'info-circle-fill' },
  { name: 'minus' },
  { name: 'minus-circle' },
  { name: 'minus-circle-fill' },
  { name: 'mic' },
  { name: 'mic-off' },
  { name: 'grid' },
  { name: 'grid-fill' },
  { name: 'eye' },
  { name: 'eye-fill' },
  { name: 'eye-off' },
  { name: 'file-text' },
  { name: 'file-text-fill' },
  { name: 'edit-pen' },
  { name: 'edit-pen-fill' },
  { name: 'email' },
  { name: 'email-fill' },
  { name: 'download' },
  { name: 'checkmark' },
  { name: 'checkmark-circle' },
  { name: 'checkmark-circle-fill' },
  { name: 'clock' },
  { name: 'clock-fill' },
  { name: 'close' },
  { name: 'close-circle' },
  { name: 'close-circle-fill' },
  { name: 'calendar' },
  { name: 'calendar-fill' },
  { name: 'car' },
  { name: 'car-fill' },
  { name: 'bell' },
  { name: 'bell-fill' },
  { name: 'bookmark' },
  { name: 'bookmark-fill' },
  { name: 'attach' },
  { name: 'play-right' },
  { name: 'play-right-fill' },
  { name: 'play-left' },
  { name: 'play-left-fill' },
  { name: 'error' },
  { name: 'error-circle' },
  { name: 'error-circle-fill' },
  { name: 'wifi' },
  { name: 'wifi-off' },
  { name: 'skip-back-left' },
  { name: 'skip-forward-right' },
  { name: 'search' },
  { name: 'setting' },
  { name: 'setting-fill' },
  { name: 'more-dot-fill' },
  { name: 'more-circle' },
  { name: 'more-circle-fill' },
  { name: 'bag' },
  { name: 'bag-fill' },
  { name: 'arrow-upward' },
  { name: 'arrow-downward' },
  { name: 'arrow-leftward' },
  { name: 'arrow-rightward' },
  { name: 'arrow-up' },
  { name: 'arrow-down' },
  { name: 'arrow-left' },
  { name: 'arrow-right' },
  { name: 'rmb' },
  { name: 'rmb-circle' },
  { name: 'rmb-circle-fill' },
  { name: 'thumb-up' },
  { name: 'thumb-up-fill' },
  { name: 'thumb-down' },
  { name: 'thumb-down-fill' },
  { name: 'coupon' },
  { name: 'coupon-fill' },
  { name: 'kefu-ermai' },
  { name: 'server-fill' },
  { name: 'server-man' },
  { name: 'scan' },
  { name: 'warning' },
  { name: 'warning-fill' },
  { name: 'google' },
  { name: 'google-circle-fill' },
  { name: 'chrome-circle-fill' },
  { name: 'ie' },
  { name: 'IE-circle-fill' },
  { name: 'github-circle-fill' },
  { name: 'android-fill' },
  { name: 'android-circle-fill' },
  { name: 'apple-fill' },
  { name: 'camera' },
  { name: 'camera-fill' },
  { name: 'pushpin' },
  { name: 'pushpin-fill' },
  { name: 'minus-square-fill' },
  { name: 'plus-square-fill' },
  { name: 'heart' },
  { name: 'heart-fill' },
  { name: 'reload' },
  { name: 'account' },
  { name: 'account-fill' },
  { name: 'minus-people-fill' },
  { name: 'plus-people-fill' },
  { name: 'integral' },
  { name: 'integral-fill' },
  { name: 'zhihu' },
  { name: 'zhihu-circle-fill' },
  { name: 'gift' },
  { name: 'gift-fill' },
  { name: 'zhifubao' },
  { name: 'zhifubao-circle-fill' },
  { name: 'weixin-fill' },
  { name: 'weixin-circle-fill' },
  { name: 'twitter' },
  { name: 'twitter-circle-fill' },
  { name: 'taobao' },
  { name: 'taobao-circle-fill' },
  { name: 'weibo' },
  { name: 'weibo-circle-fill' },
  { name: 'qq-fill' },
  { name: 'qq-circle-fill' },
  { name: 'moments' },
  { name: 'moments-circel-fill' },
  { name: 'qzone' },
  { name: 'qzone-circle-fill' },
  { name: 'facebook' },
  { name: 'facebook-circle-fill' },
  { name: 'baidu' },
  { name: 'baidu-circle-fill' },
  { name: 'share-square' },
];

export default function IconDemo() {
  const [events, setEvents] = useState<string[]>([]);
  const log = (msg: string) => setEvents((prev) => [...prev, msg]);

  const selectIcon = (name: string) => log(`图标名称已复制 ${name}`);

  return (
    <DemoPage>
      <View style={s.grid}>
        {iconList.map((item, index) => (
          <Pressable key={index} onPress={() => selectIcon(item.name)} style={s.gridItem}>
            <View style={s.gridItemIcon}>
              <UPIcon stop name={item.name} size="30" color="#909399" onClick={() => log('test')} />
            </View>
            <Text style={s.gridItemText}>{item.name}</Text>
          </Pressable>
        ))}
      </View>
      <UPIcon customPrefix="xyicon" name="light-mode" size="30" color="#909399" />

      <EventLog events={events} />
      <PropsTable rows={PROPS} />
    </DemoPage>
  );
}

/** Upstream `.u-page__grid__item` is 120x120px with a 65px icon row and 55px text row. */
const s = StyleSheet.create({
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  gridItem: {
    alignItems: 'center',
    borderColor: '#dadbde',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderRightWidth: StyleSheet.hairlineWidth,
    flexDirection: 'column',
    height: 120,
    justifyContent: 'center',
    paddingHorizontal: 5,
    width: 120,
  },
  gridItemIcon: { alignItems: 'flex-end', flexDirection: 'row', height: 65 },
  gridItemText: { color: '#909399', fontSize: 14, height: 55 },
});


