import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View, type StyleProp, type TextStyle, type ViewStyle } from 'react-native';
import { useUPConfig } from '../../config/useUPConfig';
import { useUPTheme } from '../../theme';
import { getPx, type UPDimension } from '../../utils';
import { UPIcon } from '../icon';
import { sourceSpacing } from '../shared';
export type UPSearchProps = { value?: string | number; modelValue?: string | number; defaultValue?: string | number; shape?: 'round'|'square'; bgColor?: string; placeholder?: string; clearabled?: boolean; onlyClearableOnFocused?: boolean; focus?: boolean; showAction?: boolean; actionText?: string; label?: string|number|null; inputAlign?: 'left'|'center'|'right'; disabled?: boolean; animation?: boolean; borderColor?: string; searchIconColor?: string; searchIconSize?: UPDimension; color?: string; placeholderColor?: string; searchIcon?: string; iconPosition?: 'left'|'right'; margin?: UPDimension; maxlength?: number|string; height?: UPDimension; adjustPosition?: boolean; autoBlur?: boolean; inputStyle?: StyleProp<TextStyle>; actionStyle?: StyleProp<TextStyle>; customStyle?: StyleProp<ViewStyle>; customClass?: string; onChange?: (value:string)=>void; onClear?:()=>void; onSearch?:(value:string)=>void; onCustom?:(value:string)=>void; onFocus?:(value:string)=>void; onBlur?:(value:string)=>void; onClick?:()=>void; onClickIcon?:(value:string)=>void; };
export function UPSearch(input:UPSearchProps):React.JSX.Element { const config=useUPConfig();const props={...config.props.search,...input};const {colors}=useUPTheme();const controlled=input.value??input.modelValue;const [inner,setInner]=useState(String(controlled??input.defaultValue??props.value));const [focused,setFocused]=useState(false);useEffect(()=>{if(controlled!==undefined)setInner(String(controlled));},[controlled]);const change=(value:string)=>{setInner(value);input.onChange?.(value)};const showClear=props.clearabled&&inner!==''&&(!props.onlyClearableOnFocused||focused);const icon=<Pressable onPress={()=>input.onClickIcon?.(inner)}><UPIcon color={props.searchIconColor||colors.contentColor} name={props.searchIcon} size={props.searchIconSize}/></Pressable>;
 return <View style={[{alignItems:'center',flexDirection:'row',...sourceSpacing(props.margin)},input.customStyle]} testID="up-search"><View style={{alignItems:'center',backgroundColor:props.bgColor||colors.bgColor,borderColor:props.borderColor,borderRadius:props.shape==='round'?100:4,borderWidth:props.borderColor==='transparent'?0:1,flex:1,flexDirection:props.iconPosition==='right'?'row-reverse':'row',height:getPx(props.height),paddingHorizontal:10}} testID="up-search-field">{props.label!==null?<Text style={{marginRight:4}}>{props.label}</Text>:null}{icon}<TextInput autoFocus={props.focus} editable={!props.disabled} maxLength={Number(props.maxlength)<0?undefined:Number(props.maxlength)} onBlur={()=>{setFocused(false);input.onBlur?.(inner)}} onChangeText={change} onFocus={()=>{setFocused(true);input.onFocus?.(inner)}} onSubmitEditing={()=>input.onSearch?.(inner)} placeholder={props.placeholder} placeholderTextColor={props.placeholderColor||colors.tipsColor} returnKeyType="search" style={[{color:props.color||colors.contentColor,flex:1,fontSize:14,marginHorizontal:5,padding:0,textAlign:props.inputAlign},StyleSheet.flatten(input.inputStyle)]} testID="up-search-native" value={inner}/>{showClear?<Pressable onPress={()=>{change('');input.onClear?.()}} testID="up-search-clear"><UPIcon color="#ffffff" name="close" size={11}/></Pressable>:null}</View>{props.showAction?<Pressable onPress={()=>input.onCustom?input.onCustom(inner):input.onSearch?.(inner)} testID="up-search-action"><Text style={[{color:colors.mainColor,fontSize:14,marginLeft:5,width:40},StyleSheet.flatten(input.actionStyle)]}>{props.actionText}</Text></Pressable>:null}</View> }
