import React, { useEffect, useState } from 'react';
import { Pressable, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { useUPConfig } from '../../config/useUPConfig';
import { getPx, type UPDimension } from '../../utils';
export type UPSliderProps={min?:number|string;max?:number|string;step?:number|string;value?:number|string;modelValue?:number|string;defaultValue?:number|string;isRange?:boolean;rangeValue?:[number,number];activeColor?:string;inactiveColor?:string;blockSize?:UPDimension;blockColor?:string;blockStyle?:StyleProp<ViewStyle>;disabled?:boolean;showValue?:boolean;useNative?:boolean;height?:UPDimension;innerStyle?:StyleProp<ViewStyle>;vertical?:boolean;size?:UPDimension;length?:UPDimension;customStyle?:StyleProp<ViewStyle>;customClass?:string;onChange?:(value:number)=>void;onChanging?:(value:number)=>void;
/** Source `input` event: fires on value change (same timing as `onChange`). */
onInput?:(value:number)=>void;
/** Source `start` event: fires when the user starts dragging/tapping the slider. */
onStart?:()=>void;};
export function UPSlider(input:UPSliderProps):React.JSX.Element {const config=useUPConfig();const props={...config.props.slider,...input};const external=input.value??input.modelValue;const [inner,setInner]=useState(Number(external??input.defaultValue??props.value));useEffect(()=>{if(external!==undefined)setInner(Number(external))},[external]);const min=Number(props.min),max=Number(props.max),step=Math.max(1,Number(props.step));const update=(value:number)=>{const next=Math.max(min,Math.min(max,Math.round((value-min)/step)*step+min));if(external===undefined)setInner(next);input.onChanging?.(next);input.onChange?.(next);input.onInput?.(next)};const choices:Array<number>=[];for(let value=min;value<=max;value+=step)choices.push(value);return <View style={[{alignItems:'center',flexDirection:'row'},input.customStyle]} testID="up-slider">{choices.map((value,index)=><Pressable disabled={props.disabled} key={value} onPress={()=>update(value)} onPressIn={props.onStart} style={{padding:4}} testID={`up-slider-value-${index}`}><View style={{backgroundColor:value<=inner?props.activeColor:props.inactiveColor,borderRadius:100,height:getPx(props.size),width:getPx(props.blockSize)}}/></Pressable>)}{props.showValue?<Text>{inner}</Text>:null}</View>}
